### ISSUE TITLE
relayhost in top level class not working

### ISSUE THREAD

**Issue by ceso** [camptocamp/puppet-postfix#113] opened 2015-11-30 14:58 UTC
Hi, i'm using this class in katello (Foreman) , I apply the top-level class postfix to some hosts where I defined an override value for the parameter relayhost.  When puppet agent runs in the hosts, relayhost keeps unchanged although other parameters like myorigin, or my destination work without errors.

If i use postfix::mta instead postfix top level class, they work ok, but also change other things.
Can you help me on this?
Regards

**Comment by jostmart** [comment] 2015-12-14 14:32
I can confirm this also.

**Comment by robert4man** [comment] 2016-03-29 15:49
Looks like you probably want to set mta => true
$mta and $satellite are mutually exclusive, but they are both set to false by default. Setting mta to true will include ::postfix::mta and use relayhost from the top class: $relayhost = $postfix::relayhost

**Comment by mimmus** [comment] 2016-08-17 09:23
In the default configuration of Red Hat/CentOS 7, I need to modify only 'relayhost' and 'myorigin' to have a working Postfix configuration.
Using this module, I set myorigin, relayhost (and mta => true) but Postfix complains about /etc/postfix/virtual unavailable. What do I need to set?

**Comment by raphink** [comment] 2016-08-18 07:46
@robert4man @cmachler does that mean I can mark this bug as a question and close it?

**Comment by cmachler** [comment] 2016-08-21 17:55
@raphink I would say yes mark it as question and close it.

**Closed** 2016-08-22 11:46 UTC
Labels: question
