### ISSUE TITLE
error: open database /etc/postfix/transport.db: Invalid argument when using satellite setup

### ISSUE THREAD

**Issue by knumskull** [camptocamp/puppet-postfix#101] opened 2015-09-01 18:06 UTC
I am using a satellite simple setup with following definition, but there is an issue with the transport.db database. When I am running the command `postmap /etc/postfix/transport` manually, it will work.

```
  class { '::postfix':
    satellite       => true,
    relayhost       => '[relayhost.example.com]',
    inet_interfaces => 'loopback-only',
    mynetworks      => 'localhost',
    root_mail_recipient => 'webmaster@example.com'
  }
```

`/var/log/mailllog` shows following entries.

```
Sep  1 17:20:59 localhost postfix/pickup[5616]: 8230420F9048: uid=0 from=<root>
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: error: open database /etc/postfix/transport.db: Invalid argument
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport is unavailable. open database /etc/postfix/transport.db: Invalid argument
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport lookup error for "*"
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport is unavailable. open database /etc/postfix/transport.db: Invalid argument
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport lookup error for "*"
Sep  1 17:20:59 localhost postfix/cleanup[5959]: 8230420F9048: message-id=<20150901172059.8230420F9048@host.localdomain>
Sep  1 17:20:59 localhost postfix/qmgr[5617]: 8230420F9048: from=<root@host.example.com>, size=493, nrcpt=1 (queue active)
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport is unavailable. open database /etc/postfix/transport.db: Invalid argument
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: hash:/etc/postfix/transport lookup error for "webmaster@example.com"
Sep  1 17:20:59 localhost postfix/trivial-rewrite[5960]: warning: transport_maps lookup failure
Sep  1 17:20:59 localhost postfix/qmgr[5617]: warning: connect to transport private/retry: Connection refused
Sep  1 17:20:59 localhost postfix/qmgr[5617]: 8230420F9048: to=<webmaster@example.com>, relay=none, delay=0.08, delays=0.07/0.01/0/0, dsn=4.3.0, status=deferred (mail transport unavailable)
```

**Comment by rauchrob** [comment] 2015-09-01 18:51
Have you tried adding the following to your manifest:

```
postfix::hash { '/etc/postfix/transport':
  ensure => present,
}
```

**Comment by knumskull** [comment] 2015-09-01 19:40
This is already declared in [``class postfix::mta``](https://github.com/camptocamp/puppet-postfix/blob/master/manifests/mta.pp), which is called by ``class postfix::satellite``

**Comment by knumskull** [comment] 2015-09-01 20:37
The problem is, that ``exec {"generate /etc/postfix/transport.db"`` only called, if ``/etc/postfix/transport`` is changed. But I am using an empty one. I am not sure, if this is a problem.

After adding the sample from ``transport.pp``, the hash is created and mail transfer works as expected.

~~~
postfix::transport { 'mailman.example.com':
     ensure      => present,
     destination => 'mailman',
}
~~~

Can you give any hint, what I have to insert there, if I only send all Mails to configured relayhost?

**Comment by rauchrob** [comment] 2015-09-02 07:10
On which OS are you working, by the way? Your are right, the `postmap` command is only called when `/etc/postfix/transport` changes. Maybe the `postfix` package already sets up an empty one in your case, so it doesn't get changed by puppet and henceforth the `exec` doesn't get refreshed.

**Comment by tykeal** [comment] 2015-11-11 21:49
Not saying this is the cleanest method but here's how we solved it (NOTE: RH based systems in use and this is in our smtp profile)

```puppet
  # Force transport maps to be properly built even if we aren't pushing any
  Postfix::Transport {
    require => Exec['force transport rebuild']
  }

  exec { 'force transport rebuild':
    path    => '/usr/bin:/usr/sbin:/bin',
    command => 'rm -f /etc/postfix/transport{,.db}',
    unless  => 'rpm -V postfix | grep -q transport',
    require => Class['::postfix::packages'],
  }
```

**Comment by alexjfisher** [comment] 2015-11-16 11:21
I'm encountering this on Oracle Linux 6.  Thanks @tykeal I'll try adding your workaround to my profile.

**Comment by knumskull** [comment] 2015-11-16 12:39
Hi, 
for my issue, I [forked](https://github.com/knumskull/puppet-postfix) the repo and created a  [nullclient-configuration](http://www.postfix.org/STANDARD_CONFIGURATION_README.html#null_client) for puppet-postfix.

~~~
class { '::postfix':
    nullclient => true,
    relayhost  => "[relayhost.example.com]",
  }
~~~

Until now I was not able to write some tests and clean up code for making a pull request.

**Comment by alexjfisher** [comment] 2015-11-16 17:18
I've traced the regression to https://github.com/camptocamp/puppet-postfix/commit/d3b54174d86cbe0f15cec65542907d27ebc8f5bb

Before this commit, the file resource's mode was the default from https://github.com/camptocamp/puppet-postfix/blob/master/manifests/hash.pp#L51 (0600)

The postfix RPM installs /etc/postfix/transport with mode 0644.  So since https://github.com/camptocamp/puppet-postfix/commit/d3b54174d86cbe0f15cec65542907d27ebc8f5bb (with mode now set to 0644) this resource is no longer updated and the exec is never refreshed.

Even though the exec doesn't actually run, https://github.com/camptocamp/puppet-postfix/blob/master/manifests/hash.pp#L67 still touches the /etc/postfix/transport.db file.
The zero byte file causes the postfix error.

**Comment by rauchrob** [comment] 2015-11-17 09:23
@alexjfisher: Thanks for your investigation.

So the actual problem is the `file` resource in [`manifests/hash.pp`](https://github.com/camptocamp/puppet-postfix/blob/d6f9fd21f8923fa8541b069d5fe235f9c0fb5ac3/manifests/hash.pp#L67-L70). The intention of this resource probably is to allow removal when the `ensure` attribute of the corresponding `postfix::hash` resource is set to `absent`. Therefore I would propose adding this file resource only if `$ensure == 'absent'` somehow like [this](https://github.com/rauchrob/puppet-postfix/commit/773e4d860fecc7a9661088ea462a7d2c1e142162).

**Comment by alexjfisher** [comment] 2015-11-17 09:31
Yeah, i figured the only point in the file resource would be when ```ensure => absent```
But is postfix any happier to be told to read a file that doesn't exist?

Perhaps an extra exec that runs postmap if the .db file is empty would be a good/safe fix.

**Comment by rauchrob** [comment] 2015-11-17 09:43
@alexjfisher Yes, you are right. I already thought about this option but somehow missed the problem you just mentioned. Introducing something `Exec['initial postmap run for $name']` would also be much more expressive.

**Comment by alexjfisher** [comment] 2015-11-17 11:19
@rauchrob I'm currently testing https://github.com/alexjfisher/puppet-postfix/commit/6b60e27b0c030606ee72609769864548051e90d4 and will create a PR if/when I'm happy it works :)

**Comment by rauchrob** [comment] 2015-11-18 10:40
@alexjfisher I think a `case` statement on the `$ensure` parameter is generally a good practice, because it is much more readable. Therefore I've sketched an alternative approach rauchrob@88a8911, which should be equivalent to yours. I will also add some refactoring soon.

**Comment by rauchrob** [comment] 2015-11-18 11:01
I have added some refactoring, see [here](https://github.com/camptocamp/puppet-postfix/compare/master...rauchrob:4d54af74262408bd5d396b505d49121773957f69).

Maybe you finde something useful within your PR.

**Comment by alexjfisher** [comment] 2015-11-18 12:17
@rauchrob LGTM.  It looks cleaner/better than mine.  Getting rid of the File defaults is a good idea too.  It took me *ages* to spot that mode was being managed before https://github.com/camptocamp/puppet-postfix/commit/d3b54174d86cbe0f15cec65542907d27ebc8f5bb (just looking at the diff certainly doesn't help!)

I was going for the smallest patch, but https://github.com/camptocamp/puppet-postfix/pull/112/files#diff-c22e84f77a74507b3cecb71acfdc4c15R89 is admittedly quite nasty.

Do you want to create a PR too and then @mcanevet can perhaps decide which one he prefers to merge?

**Comment by rauchrob** [comment] 2015-11-19 08:50
> Do you want to create a PR too and then @mcanevet can perhaps decide which one he prefers to merge?

@alexjfisher Ok.

**Comment by poikilotherm** [comment] 2016-05-20 12:44
Hi,

any progress on this? I just ran into this issue on a newly setup RH 7 system. Using the `postmap /etc/postfix/transport` command solved it.

Thanks in advance!

**Comment by rauchrob** [comment] 2016-05-20 12:59
I guess both me and alexjfisher forgot to actually create a PR. I will try to have a look at it soon...

**Comment by alexjfisher** [comment] 2016-05-20 14:20
@rauchrob I opened https://github.com/camptocamp/puppet-postfix/pull/112 at the time.
The much more recent https://github.com/camptocamp/puppet-postfix/pull/135 also fixes this I think.

@mcanevet Are you able to look at merging a fix for this?
Thanks

**Comment by mimmus** [comment] 2016-08-17 11:01
Issue still present both with virtual and transport files on Red Hat 7.2

**Comment by alexjfisher** [comment] 2017-08-15 09:49
@raphink Sorry for the delay (almost exactly a year after you asked!), but yes, I can confirm this is no longer an issue in the latest release. :)

**Closed** 2017-08-15 12:35 UTC
