### ISSUE TITLE
The virtual.db and transport.db files are created empty

### ISSUE THREAD

**Issue by gothicx** [camptocamp/puppet-postfix#130] opened 2016-04-28 12:31 UTC
RHEL 7.2:

```
Notice: /Stage[main]/Postfix::Mta/Postfix::Hash[/etc/postfix/virtual]/File[/etc/postfix/virtual.db]/ensure: created
Notice: /Stage[main]/Postfix::Mta/Postfix::Hash[/etc/postfix/transport]/File[/etc/postfix/transport.db]/ensure: created

-rw-r--r--. 1 root root  13K Jan 26  2014 transport
-rw-------. 1 root root    0 Apr 28 14:25 transport.db
-rw-r--r--. 1 root root  13K Jan 26  2014 virtual
-rw-------. 1 root root    0 Apr 28 14:25 virtual.db

```

**Comment by shollingsworth** [comment] 2016-05-06 22:03
Having the same problem...

**Comment by alexjfisher** [comment] 2016-05-20 14:14
This is a duplicate of https://github.com/camptocamp/puppet-postfix/issues/101 ?

**Comment by gothicx** [comment] 2016-05-20 16:52
It looks like..

**Comment by mimmus** [comment] 2016-08-17 10:13
Same problem on RH 7.2

**Comment by raphink** [comment] 2016-08-17 13:35
#135 was merged. Does it fix this?

**Comment by mimmus** [comment] 2016-08-22 12:39
Does #135  was merged in 1.3.1?

**Comment by raphink** [comment] 2016-08-22 12:46
@mimmus no, it's not released yet.

**Closed** 2021-04-27 07:49 UTC
Labels: wontfix
